version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "6378:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - redis1
      - redis2

  redis1:
    image: redis:latest
    container_name: redis1
    ports:
      - "6370:6379"  # Mapeia a porta 6379 do container para a porta 6370 do host
    networks:
      - app_network

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - "6380:6379"  # Mapeia a porta 6379 do container para a porta 6380 do host
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
